# Generated by Django 5.1.2 on 2024-11-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_payment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(
                blank=True, max_length=127, null=True, verbose_name="session"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="url",
            field=models.URLField(
                blank=True, max_length=511, null=True, verbose_name="url"
            ),
        ),
    ]
