# Generated by Django 5.1.2 on 2024-11-05 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessons",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="materials.course",
                verbose_name="course",
            ),
        ),
        migrations.AddField(
            model_name="lessons",
            name="url",
            field=models.TextField(blank=True, null=True, verbose_name="url"),
        ),
    ]
